In [ ]:
# check numpy version
import numpy as np
#1d , 2d , 3d ,
# np.__version__


'1.26.4'

In [79]:
# lst = 
# ar1 = np.array([1,2,"3",4,5])
ar1 = np.array([1,2,3,4,5],ndmin=6)

ar1
# print(type(ar1))

array([[[[[[1, 2, 3, 4, 5]]]]]])

In [10]:
##when you have to create an array in a range
ar2 = np.arange(1,10)
ar2 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr3 = np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [15]:
arr4 = np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr5 = np.linspace(0,20,50)
arr5

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [22]:
##
arr6 = np.arange(1,31).reshape(5,6)
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [26]:
# arr7 = np.random.randint(1,100,10)
arr7 = np.random.random(10)
arr7

array([0.04494289, 0.15786924, 0.24984529, 0.02269956, 0.54178852,
       0.49759205, 0.04528527, 0.4853923 , 0.44033829, 0.51131519])

In [38]:
arr8 = np.arange(60).reshape((12,5))
print(arr8.shape)
# arr8.dtype
# arr8.size
# arr8.ndim
arr9 = arr8.T.shape
arr9

(12, 5)


(5, 12)

In [33]:
#mutlidimension array convert 1d 
arr8.ravel()
# arr8.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [41]:
###indexing and slicing 
##1d array
##2d array -- [row start : rowend:rowskip, col start : col end : col skip]
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [57]:
# arr8[3:4,2:3] = 100
arr8[9:10,4:5][0][0]

49

In [59]:
arr8[::-1,::-1]

array([[ 59,  58,  57,  56,  55],
       [ 54,  53,  52,  51,  50],
       [ 49,  48,  47,  46,  45],
       [ 44,  43,  42,  41,  40],
       [ 39,  38,  37,  36,  35],
       [ 34,  33,  32,  31,  30],
       [ 29,  28,  27,  26,  25],
       [ 24,  23,  22,  21,  20],
       [ 19,  18, 100,  16,  15],
       [ 14,  13,  12,  11,  10],
       [  9,   8,   7,   6,   5],
       [  4,   3,   2,   1,   0]])

In [62]:
##3d array
arr10 = np.arange(225).reshape(3,15,5)
arr10

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [ ]:
##slicing in 3d array 
## syntax -
#[table start : table end : table skip, row start : row end : row skip, col start : col end : col skip]

In [66]:
arr10[0:,1:4,2:4]

array([[[  7,   8],
        [ 12,  13],
        [ 17,  18]],

       [[ 82,  83],
        [ 87,  88],
        [ 92,  93]],

       [[157, 158],
        [162, 163],
        [167, 168]]])

In [72]:
np.max(arr8)
np.min(arr8)
np.sum(arr8)
np.mean(arr8)
np.median(arr8)
np.std(arr8)

19.44830041131844

In [73]:
arr8.sort()

In [ ]:
arr11 = np.array([2,5,1,9])
arr12 = np.array([2,5,1,9])
# arr11.argsort()
##2 5 1 9 
##0 1 2 3

arr11 * 2

array([ 4, 10,  2, 18])